### ISSUE TITLE
[Font Bakery Dashboard] fail to create family: Bebas Neue

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery-dashboard#130]
[full report](https://fontbakery.graphicore.de/dispatcher/process/3ca21271-33b3-4fb8-baa8-1323a4545ec9)

# Step # 1 Quality Assurance

**finished: FAILED**

Failing with reason: see diffbrowsers

### Task BrowsersDiffsAndPreviews FAILED

**@graphicore** Browsers diffs and previews are failing.

see exception.

the worker log gives me:

```
2019-10-07 18:03:44,284:diffbrowsers.diffbrowsers:INFO:Generating glyphs_all gifs
2019-10-07 18:03:44,478:FB_WORKER:INFO:DONE! docid: 2585bd024e70b5f26bee25737b1f6deb7ebe76552471fe37a3390bb79fbaa25e
2019-10-07 18:03:44,490:grpc._channel:ERROR:Exception iterating requests!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 192, in consume_request_iterator
    request = next(request_iterator)
  File "/var/python/worker/storageclient.py", line 130, in <genexpr>
    storage_items = (make_storage_item(message, str(index))\
  File "/var/python/worker/diff_tools_shared.py", line 228, in <genexpr>
    files_msgs = (self._make_result(result_name) for result_name in result_dirs)
  File "/var/python/worker/diff_tools_shared.py", line 219, in _make_result
    with open(abs_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkph88u12/diffbrowsers/Regular/Browser_Previews/BebasNeue-Regular/glyphs_all_15pt/gifs/Desktop_Windows_10_firefox_62.0_.gif'

```

Report…

### EXCEPTION
```
Can't create (all) results:
Traceback (most recent call last):
  File "/var/python/worker/diff_tools_shared.py", line 251, in finalize
    self._make_results()
  File "/var/python/worker/diff_tools_shared.py", line 231, in _make_results
    for result_name, storage_key in zip(result_dirs, storage_keys):
  File "/var/python/worker/storageclient.py", line 133, in put
    for storageKey in self._client.Put(storage_items):
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1570464224.483900649","description":"Error received from peer ipv4:10.51.249.86:50051","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Connection reset by peer","grpc_status":14}"
>

```

### Preparation Logs
 * `Added file "after/BebasNeue-Regular.ttf".`
 * `Added file "after/METADATA.pb".`
 * `Added file "after/OFL.txt".`

*started* Mon Oct 07 2019 16:01:28 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Oct 07 2019 16:03:44 GMT+0000 (Coordinated Universal Time)

**Comment by graphicore** [comment]
```
2019-10-07 18:03:44,490:grpc._channel:ERROR:Exception iterating requests!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 192, in consume_request_iterator
    request = next(request_iterator)
  File "/var/python/worker/storageclient.py", line 130, in <genexpr>
    storage_items = (make_storage_item(message, str(index))\
  File "/var/python/worker/diff_tools_shared.py", line 228, in <genexpr>
    files_msgs = (self._make_result(result_name) for result_name in result_dirs)
  File "/var/python/worker/diff_tools_shared.py", line 219, in _make_result
    with open(abs_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkph88u12/diffbrowsers/Regular/Browser_Previews/BebasNeue-Regular/glyphs_all_15pt/gifs/Desktop_Windows_10_firefox_62.0_.gif'
```
[I can't reproduce](https://fontbakery.graphicore.de/dispatcher/process/4429b763-58d1-4180-b242-fee904656ff5). Maybe we need to catch the Error and try to handle it gracefully.

**Comment by vv-monsalve** [comment]
Going through [the process](https://fontbakery.graphicore.de/dispatcher/process/7d9b4410-8e89-4b97-a49c-ee55ebfdb964) again, the Error didn't emerge this time
