### ISSUE TITLE
PullRequest: A pull request already exists

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery-dashboard#143]
e.g. here: http://localhost:3000/dispatcher/process/de44777e-8618-41ca-bc33-b50b10877f84

I want the Dispatcher to just amend the new report to the existing PR. We're pushing to the same branch with `force` anyways, so this failure is after the fact.

```
DEBUG _push: graphicore graphicore/googleFonts Font_Bakery_Dispatcher/ofl_abeezee                                                                                                                     
DEBUG remote.push +refs/heads/dispatch_branch:refs/heads/Font_Bakery_Dispatcher/ofl_abeezee                                                                                                           
DEBUG _push DONE                                                                                   
# […]
DEBUG _gitHubPR: graphicore:Font_Bakery_Dispatcher/ofl_abeezee => graphicore/googleFonts master                                                                                                       
DEBUG HTTP POST: 422 url: https://api.github.com/repos/graphicore/googleFonts/pulls headers: { date: 'Mon, 14 Oct 2019 18:15:33 GMT',                                                                 
  'content-type': 'application/json; charset=utf-8',                                                                                                                                                  
  'content-length': '261',                       
  connection: 'close',                                                                             
  server: 'GitHub.com',                                                                                                                                                                               
  status: '422 Unprocessable Entity',            
  'x-ratelimit-limit': '5000',                                                                     
  'x-ratelimit-remaining': '4999',                                                                 
  'x-ratelimit-reset': '1571080533',             
  'x-oauth-scopes': 'public_repo, user:email',                                                     
  'x-accepted-oauth-scopes': '',                                                                                                                                                                      
  'x-oauth-client-id': '...',                                                     
  'x-github-media-type': 'github.v3',                                                                                                                                                                 
  'access-control-expose-headers':               
   'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',     
  'access-control-allow-origin': '*',                                                              
  'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',                     
  'x-frame-options': 'deny',                                                                                                                                                                          
  'x-content-type-options': 'nosniff',           
  'x-xss-protection': '1; mode=block',                                                             
  'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',                                                                                                                     
  'content-security-policy': "default-src 'none'",                                                 
  'x-github-request-id': '...' } json: { message: 'Validation Failed',                                                                                                
  errors:                                                                                          
   [ { resource: 'PullRequest',                  
       code: 'custom',                           
       message:                                                                                                                                                                                       
        'A pull request already exists for graphicore:Font_Bakery_Dispatcher/ofl_abeezee.' } ],                                                                                                       
  documentation_url:                                                                                                                                                                                  
   'https://developer.github.com/v3/pulls/#create-a-pull-request' }                                
ERROR In dispatch to: ofl/abeezee branch: Font_Bakery_Dispatcher/ofl_abeezee { Error: (422) Validation Failed [POST url: https://api.github.com/repos/graphicore/googleFonts/pulls] Errors:           
 * [custom] PullRequest: A pull request already exists for graphicore:Font_Bakery_Dispatcher/ofl_abeezee.                                                                                             
    at IncomingMessage.res.on (/var/javascript/node/GitHubOperationsServer.js:220:33)                                                                                                                 
    at IncomingMessage.emit (events.js:198:15)                                                                                                                                                        
    at endReadableNT (_stream_readable.js:1139:12)                                                                                                                                                    
    at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 422, isHTTPError: true }       

```

**Comment by graphicore** [comment]
Starts to work: [process](http://localhost:3000/dispatcher/process/de44777e-8618-41ca-bc33-b50b10877f84)
[PR](https://github.com/graphicore/googleFonts/pull/43)
