### ISSUE TITLE
[gRPC/cache]  read fails with "Stream removed"

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery-dashboard#56]
This causes a number of (random?) jobs to finish exceptionally. [copy of error at the bottom]
 
It seems like this is a minor load issue, and we should probably try to reach the cache again after some time, or maybe reschedule the job.

I'm picking randomly a few sample family reports when I post links here, but there are **45 affected reports**. All from `GoogleFontsAPI/production`, which is usually the first collection to run, when I start the test-run.

http://35.225.170.228/report/8cba7bf5-5c87-4e3b-8f43-1058d9016c02 (scroll to the bottom)

Nevertheless, it affects a number of reports:

* in `job 0` (quite common): http://35.225.170.228/report/56a3e80b-bb3b-47b9-bee5-155eb0a63b58
* in in `job 1` (sometime): http://35.225.170.228/report/c96a10d8-d514-4536-851b-a9826a9fb698
* in `job 1`, `job 2` and `job 6` (it's a big family) :http://35.225.170.228/report/4e7c09bf-117d-418b-b4d8-e233d3d696a2

Including a screenshot  from http://35.225.170.228/report/4a1ce9b8-35dc-4e74-982e-deb962b298ed 
It has times in it. The report was created at 12/19/2017, 9:06:13 PM which is around the time the whole test run started. `job 2` was finished at  12/19/2017, 9:06:24 PM by the exception. The dispatcher created the job at 12/19/2017, 9:06:24 PM.

![selection_191](https://user-images.githubusercontent.com/393132/34191776-fe93e984-e549-11e7-8eb0-8cec1d76138c.png)

So all these times are very close to the start of the whole test-run. And all the affected families are early in the alphabet, which is afaik the order from the fonts api, between `Abel` and `Exo 2`. This hints that the issue appears when a lot of read and write requests hit the cache process, at the beginning of the run when the cache is still written but also already read:

![selection_190](https://user-images.githubusercontent.com/393132/34191668-1f2e3b32-e549-11e7-9fb8-5531c983833d.png)

(taken from http://35.225.170.228/dashboard at the creation time of this issue)

```
Traceback (most recent call last):
  File "/var/python/worker/fontbakeryworker.py", line 121, in _run
    fonts = self._prepare(tmpDirectory)
  File "/var/python/worker/fontbakeryworker.py", line 75, in _prepare
    files = self._cache.get(job.cacheKey).files
  File "/var/python/worker/cacheclient.py", line 56, in get
    any = self._client.Get(cacheKey);
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 485, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 435, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Stream removed)>
```

**Comment by graphicore** [comment]
Also do this: https://googlecloudplatform.github.io/google-cloud-python/latest/logging/usage.html#integration-with-python-logging-module so these errors are shown in the gcloud stackdriver interface. It will have to remain reasonably platform independent though, i.e. if we're running on gcloud, we can use this extra logger, otherwise we don't.

**Comment by graphicore** [comment]
This looks like a worthwhile approach (with sample code): https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2583#issuecomment-256026510

**Comment by graphicore** [comment]
Maybe related: https://github.com/grpc/grpc/issues/9779

**Comment by graphicore** [comment]
The exponential timeout retry/back-off strategy seems to have solved this.
